version: '3.3'
services:

  indypool:
    network_mode: host
    image: "teamblockchain/indy-pool:1.15.0"
    ports:
      - "9701-9708:9701-9708"
    container_name: indypool


# -------------------- Corda nodes -----------------------


  tccorda:
    network_mode: host
    build:
      context: ./build/nodes/TreatmentCenter
      dockerfile: Dockerfile-corda
#    ports:
#      - "10101:10101"
#      - "10102:10102"
#      - "10103:10103"
    container_name: tccorda
    environment:
      - RUST_LOG=trace
    deploy:
      resources:
        limits:
          memory: 1536m


  mfcorda:
    network_mode: host
    build:
      context: ./build/nodes/Manufacture
      dockerfile: Dockerfile-corda
#    ports:
#      - "10001:10001"
#      - "10002:10002"
#      - "10003:10003"
    container_name: mfcorda
    environment:
      - RUST_LOG=trace
    deploy:
      resources:
        limits:
          memory: 1536m


  notary:
    network_mode: host
    build:
      context: ./build/nodes/Notary
      dockerfile: Dockerfile-corda
#    ports:
#      - "10701:10701"
#      - "10702:10702"
#      - "10703:10703"
    container_name: notary
    deploy:
      resources:
        limits:
          memory: 1536m



# -------------------- Spring nodes -----------------------


  mfweb:
    network_mode: host
    build:
      context: ./webapp
      dockerfile: Dockerfile-web
#    ports:
#      - "8081:8081"
    environment:
      - "SPRING_PROFILES_ACTIVE=manufacture"
    container_name: mfweb
    deploy:
      resources:
        limits:
          memory: 512m


  tcweb:
    network_mode: host
    build:
      context: ./webapp
      dockerfile: Dockerfile-web
#    ports:
#      - "8082:8082"
    environment:
      - "SPRING_PROFILES_ACTIVE=treatmentcenter"
    container_name: tcweb
    deploy:
      resources:
        limits:
          memory: 512m

  # -------------------- Indy agents -----------------------
  agent94:
    image: teamblockchain/indy-agent-python:2a838e3
    ports:
      - "8094:8094"
    environment:
      - "PORT=8094"
    command: "python3.6 indy-agent.py 8094 --hostname=18.216.172.155"
    container_name: agent94

  agent95:
    image: teamblockchain/indy-agent-python:2a838e3
    ports:
      - "8095:8095"
    environment:
      - "PORT=8095"
    command: "python3.6 indy-agent.py 8095 --hostname=18.216.172.155"
    container_name: agent95

  agent96:
    image: teamblockchain/indy-agent-python:2a838e3
    ports:
      - "8096:8096"
    environment:
      - "PORT=8096"
    command: "python3.6 indy-agent.py 8096 --hostname=18.216.172.155"
    container_name: agent96

  agentInitiator:
    network_mode: host
    image: alpine:3.6
    container_name: agentInitiator
    depends_on:
      - agent94
      - agent95
      - agent96
    command: sh -c 'sleep 10; /usr/bin/wget --spider http://localhost:8094/; /usr/bin/wget --spider http://localhost:8095/; /usr/bin/wget --spider http://localhost:8096/'
